logging:
  level:
    root: INFO
    az.pashabank: DEBUG

spring:
  application:
    name: investigate-bff-webflux

server:
  port: 8082

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - prometheus
          - metrics
          - env
  metrics:
    tags:
      application: ${spring.application.name}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
